[package]
name = "mlfq"
version = "0.1.0"
edition = "2021"
authors = ["Evan Drake <evanmdrake@icloud.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
